name: gbl_fishing_new
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/background2.jpg
    - assets/icon/background3.jpg
    - assets/icon/background4.jpg
